version: '3'

services:
  
  rabbitmq:
    image: rabbitmq:3.7.5
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    hostname: server
    volumes:
      - ./server:/src
    ports:
      - '8000:8000'
    command: >
      bash -c '
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000'
    depends_on:
      - rabbitmq
  
  worker:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/src
    command: celery -A server worker -l info
    depends_on:
      - rabbitmq
